# Generated by Django 3.1 on 2020-09-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformyLatajace',
            fields=[
                ('id_drona', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=30)),
                ('pojemonosc_akumulatora', models.IntegerField(db_column='Pojemonosc_akumulatora')),
                ('predkosc_przelotowa', models.IntegerField(blank=True, db_column='Predkosc_przelotowa', null=True)),
                ('oswietlenie', models.BooleanField(blank=True, db_column='Oswietlenie', null=True)),
            ],
            options={
                'db_table': 'Platformy_latajace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PodzialTrasy',
            fields=[
                ('id_odcnika', models.AutoField(primary_key=True, serialize=False)),
                ('poczatek_odcinka', models.IntegerField(db_column='Poczatek_odcinka')),
                ('koniec_odcinka', models.IntegerField(db_column='Koniec_odcinka')),
                ('poziom_zagrozenia', models.IntegerField(db_column='Poziom_zagrozenia')),
            ],
            options={
                'db_table': 'Podzial_trasy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trasy',
            fields=[
                ('id_trasy', models.AutoField(primary_key=True, serialize=False)),
                ('stacja_poczatek', models.CharField(db_column='Stacja_poczatek', max_length=30)),
                ('stacja_koniec', models.CharField(db_column='Stacja_koniec', max_length=30)),
                ('dlugosc_trasy', models.IntegerField(db_column='Dlugosc_trasy')),
                ('nazwa_trasy', models.CharField(db_column='Nazwa_trasy', max_length=30)),
            ],
            options={
                'db_table': 'Trasy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypyOtoczenia',
            fields=[
                ('id_otoczenia', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(db_column='Typ', max_length=30)),
            ],
            options={
                'db_table': 'Typy_otoczenia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id_uzytkownika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(db_column='Imie', max_length=30)),
                ('nazwisko', models.CharField(db_column='Nazwisko', max_length=30)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=30, null=True)),
                ('numer_telefonu', models.IntegerField(blank=True, db_column='Numer_telefonu', null=True)),
                ('haslo', models.CharField(blank=True, db_column='Haslo', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Uzytkownicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zagrozenia',
            fields=[
                ('id_zagrozenia', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(blank=True, db_column='Typ', max_length=30, null=True)),
                ('skala_zagrozenia', models.SmallIntegerField(blank=True, db_column='Skala_zagrozenia', null=True)),
            ],
            options={
                'db_table': 'Zagrozenia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zgloszenia',
            fields=[
                ('id_zgloszenia', models.AutoField(primary_key=True, serialize=False)),
                ('lokalizacja_gps_n', models.CharField(db_column='Lokalizacja_gps_N', max_length=30)),
                ('lokalizacja_gps_e', models.CharField(db_column='Lokalizacja_gps_E', max_length=30)),
                ('zgloszenie_sluzbon', models.BooleanField(blank=True, db_column='Zgloszenie_sluzbon', null=True)),
            ],
            options={
                'db_table': 'Zgloszenia',
                'managed': False,
            },
        ),
    ]
