# Generated by Django 3.1 on 2020-11-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenia',
            name='zdjecie',
            field=models.BinaryField(blank=True, db_column='Zdjecie'),
        ),
    ]
