# Generated by Django 3.1 on 2020-11-09 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0002_auto_20201109_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenia',
            name='data_zgloszenia',
            field=models.DateTimeField(db_column='Data_zgloszenia', default=datetime.datetime.now),
        ),
    ]
