# Generated by Django 3.1 on 2020-11-09 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0003_auto_20201109_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenia',
            name='data_zgloszenia',
            field=models.DateTimeField(db_column='Data_zgloszenia', default=datetime.date(2020, 11, 9)),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='godz_zgloszenia',
            field=models.DateTimeField(db_column='Godz_zgloszenia', default=datetime.time(17, 22, 15, 919629)),
        ),
    ]
