# Generated by Django 3.1 on 2020-11-09 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0004_auto_20201109_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenia',
            name='data_zgloszenia',
            field=models.DateTimeField(blank=True, db_column='Data_zgloszenia', default=datetime.date(2020, 11, 9)),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='godz_zgloszenia',
            field=models.DateTimeField(blank=True, db_column='Godz_zgloszenia', default=datetime.time(17, 49, 53, 619980)),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='id_drona',
            field=models.ForeignKey(blank=True, db_column='id_drona', on_delete=django.db.models.deletion.DO_NOTHING, to='rod.drony'),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='id_odcinka_trasy',
            field=models.ForeignKey(blank=True, db_column='id_odcinka_trasy', on_delete=django.db.models.deletion.DO_NOTHING, to='rod.podzialtrasy'),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='id_trasy',
            field=models.ForeignKey(blank=True, db_column='id_trasy', on_delete=django.db.models.deletion.DO_NOTHING, to='rod.trasy'),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='lokalizacja_gps',
            field=models.CharField(blank=True, db_column='Lokalizacja_gps', max_length=30),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='rodzaj_zagrozenia',
            field=models.ForeignKey(blank=True, db_column='Rodzaj_zagrozenia', on_delete=django.db.models.deletion.DO_NOTHING, to='rod.zagrozenia'),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='zarejestrowane',
            field=models.BooleanField(blank=True, db_column='Zarejestrowane', default=False),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='zgloszenie_sluzbom',
            field=models.BooleanField(blank=True, db_column='Zgloszenie_sluzbom', default=False),
        ),
    ]
