# Generated by Django 3.1 on 2020-11-09 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0005_auto_20201109_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenia',
            name='data_zgloszenia',
            field=models.DateTimeField(blank=True, db_column='Data_zgloszenia', default=datetime.date(2020, 11, 9), null=True),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='godz_zgloszenia',
            field=models.DateTimeField(blank=True, db_column='Godz_zgloszenia', default=datetime.time(17, 51, 25, 378907), null=True),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='id_drona',
            field=models.ForeignKey(blank=True, db_column='id_drona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rod.drony'),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='id_odcinka_trasy',
            field=models.ForeignKey(blank=True, db_column='id_odcinka_trasy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rod.podzialtrasy'),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='id_trasy',
            field=models.ForeignKey(blank=True, db_column='id_trasy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rod.trasy'),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='rodzaj_zagrozenia',
            field=models.ForeignKey(blank=True, db_column='Rodzaj_zagrozenia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rod.zagrozenia'),
        ),
    ]
