# Generated by Django 3.1 on 2020-11-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0009_delete_obrazek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenia',
            name='data_zgloszenia',
            field=models.DateField(blank=True, db_column='Data_zgloszenia', null=True),
        ),
        migrations.AlterField(
            model_name='zgloszenia',
            name='godz_zgloszenia',
            field=models.TimeField(blank=True, db_column='Godz_zgloszenia', null=True),
        ),
    ]
