# Generated by Django 3.1 on 2020-11-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rod', '0010_auto_20201109_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zgloszenia',
            name='id_odcinka_trasy',
        ),
    ]
